[pytest]
testpaths = tests
addopts = --import-mode=prepend
norecursedirs =
    .git
    .venv
    venv
    build
    dist
    site-packages
    tools-src
    3rdparty
    third_party
python_files = test_*.py
