// SaxoFlow starter formal harness
//
// Purpose:
// - Instantiate your DUT in a small verification wrapper.
// - Declare symbolic inputs with (* anyseq *) or (* anyconst *).
// - Add assumptions for legal environment behavior.
// - Add assertions for the properties you want to prove.
//
// Suggested workflow:
// 1. Replace module/port names to match your DUT.
// 2. Keep only one or two simple assumptions/assertions at first.
// 3. Run BMC first, then try a prove task once BMC is clean.

module formal_top;
    // Use the global formal clock generated by Yosys/SymbiYosys.
    (* gclk *) reg clk;

    // Example symbolic stimulus. Rename or add signals to match your DUT.
    (* anyseq *) reg req;
    (* anyseq *) reg ack;

    // Example observed DUT signal.
    wire done;

    // Replace this example instance with your actual DUT and ports.
    dut u_dut (
        .clk(clk),
        .req(req),
        .ack(ack),
        .done(done)
    );

    // Track whether $past(...) is safe to use.
    reg past_valid = 1'b0;

    always @(posedge clk) begin
        past_valid <= 1'b1;

        // Example environment rule:
        // request and acknowledge should not be high at the same time.
        assume (!(req && ack));

        if (!past_valid) begin
            // Put power-on constraints here if your DUT has no reset.
            // Example:
            // assume(done == 1'b0);
        end else begin
            // Example safety property:
            // if done was low and ack is low, done should not rise unexpectedly.
            if (!$past(done) && !$past(ack)) assert (!done);

            // Add your real protocol, arithmetic, or state-machine properties here.
            // Good first properties for learners:
            // - illegal state is unreachable
            // - output only changes after a valid input event
            // - counter never exceeds a bound
            // - request is eventually followed by acknowledge (for cover/prove tasks)
        end
    end

    // Example cover statement for exploration.
    // Uncomment after the harness matches your DUT behavior.
    // always @(posedge clk) begin
    //   cover (past_valid && done);
    // end
endmodule
