/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "source/rtl/verilog/adder.v:1.1-11.10" *)
module adder(a, b, sum);
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _01_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _02_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _03_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _04_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _05_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _06_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _07_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _08_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _09_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _10_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _11_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _12_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _13_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire _14_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _15_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _16_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _17_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _18_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _19_;
  (* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _20_;
  (* src = "source/rtl/verilog/adder.v:2.23-2.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "source/rtl/verilog/adder.v:3.23-3.24" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "source/rtl/verilog/adder.v:4.23-4.26" *)
  output [4:0] sum;
  wire [4:0] sum;
  assign sum[1] = _06_ ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _00_;
  assign sum[2] = _07_ ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _01_;
  assign sum[3] = _08_ ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _02_;
  assign sum[0] = b[0] ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  a[0];
  assign _06_ = b[1] ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  a[1];
  assign _07_ = b[2] ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  a[2];
  assign _08_ = b[3] ^(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)  a[3];
  assign _00_ = b[0] &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  a[0];
  assign _11_ = b[1] &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  a[1];
  assign _12_ = b[2] &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  a[2];
  assign _13_ = b[3] &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)  a[3];
  assign _15_ = _06_ &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _00_;
  assign _16_ = _08_ &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _12_;
  assign _17_ = _18_ &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _01_;
  assign _18_ = _08_ &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _07_;
  assign _19_ = _07_ &(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _01_;
  assign _01_ = _11_ |(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _15_;
  assign _20_ = _13_ |(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _16_;
  assign sum[4] = _20_ |(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)  _17_;
  assign _02_ = _12_ |(* src = "source/rtl/verilog/adder.v:9.18-9.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _19_;
  assign { _04_, _03_ } = { 1'h0, sum[4] };
  assign { _09_, _05_ } = { 1'h0, sum[0] };
  assign { _14_, _10_ } = { 1'h0, _00_ };
endmodule
