# saxoflow_agenticai/config/model_config.yaml

default_provider: groq
default_model: llama3-8b-8192

agent_models:
  rtlgen:
    provider: groq
    model: llama3-8b-8192
  tbgen:
    provider: together
    model: mistralai/Mixtral-8x7B-Instruct-v0.1
  fpropgen:
    provider: fireworks
    model: accounts/fireworks/models/llama4-maverick-instruct-basic
  rtlreview:
    # provider: openrouter
    # model: deepseek/deepseek-r1-0528-qwen3-8b:free
    provider: googleaistudio
    model: gemini-2.0-flash    
  tbreview:
    provider: googleaistudio
    model: gemini-2.0-flash
  fpropreview:
    provider: googleaistudio
    model: gemini-2.0-flash
  report:
    provider: mistral
    model: mistral-large-latest # or whatever is correct for the API
# Add more as needed

providers:
  groq:
    model: llama3-8b-8192
  together:
    model: mistralai/Mixtral-8x7B-Instruct-v0.1
  fireworks:
    model: accounts/fireworks/models/firellava-13b
  openrouter:
    model: deepseek/deepseek-r1-0528-qwen3-8b:free
  mistral:
    model: mistral-large-latest
  googleaistudio:
    model: gemini-2.0-flash
