TOOL_DESCRIPTIONS = {
    # --- Common tools ---
    "iverilog": "[Simulation] Icarus Verilog: Open-source Verilog-2005 simulator for RTL design verification.",
    "verilator": "[Simulation] Verilator: High-performance SystemVerilog simulator (synthesizable subset only).",
    "gtkwave": "[Debug] GTKWave: Waveform viewer for VCD/FST files generated by simulators.",
    "vscode": "[IDE] VS Code: Versatile IDE for RTL/HDL with syntax highlighting and extension support.",

    # --- Shared design tools ---
    "yosys": "[Synthesis] Yosys: Open-source synthesis tool for Verilog RTL (supports most of Verilog-2005).",
    "symbiyosys": "[Formal] SymbiYosys: Formal verification frontend for Yosys and SMT-based solvers.",

    # --- FPGA-specific tools ---
    "nextpnr": "[Implementation – FPGA] nextpnr: Open-source place and route tool for FPGAs (iCE40, ECP5, Gowin).",
    "openfpgaloader": "[Programming – FPGA] openFPGALoader: Flexible bitstream uploader for a wide range of FPGA boards.",

    # --- ASIC-specific tools ---
    "openroad": "[Implementation – ASIC] OpenROAD: Full digital ASIC flow for RTL-to-GDSII (P&R, CTS, optimization).",
    "magic": "[Layout – ASIC] Magic: VLSI layout editor with DRC support for custom and standard-cell design.",
    "klayout": "[Layout Viewer – ASIC] KLayout: Powerful GDSII layout viewer for inspecting and validating layouts.",
    "netgen": "[LVS – ASIC] Netgen: Netlist comparison and Layout vs. Schematic (LVS) tool for ASIC flows."
}
